name: verify

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 17 ]

    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          cache: gradle
          distribution: zulu

      - id: build
        run: ./gradlew build --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
